# Generated by Django 3.1.2 on 2020-12-15 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner', verbose_name='轮播图片')),
                ('index', models.IntegerField(default=0, verbose_name='轮播顺序')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '首页轮播',
                'verbose_name_plural': '首页轮播',
                'ordering': ['-ctime'],
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('goods_num', models.IntegerField(default=0, verbose_name='库存数')),
                ('shop_price', models.FloatField(default=0, verbose_name='本店价格')),
                ('goods_brief', models.TextField(max_length=500, verbose_name='商品简短描述')),
                ('goods_desc', models.ImageField(upload_to='goods/desc/images/', verbose_name='商品具体描述')),
                ('ship_free', models.BooleanField(default=True, verbose_name='是否承担运费')),
                ('goods_front_image', models.ImageField(upload_to='goods/detail/images', verbose_name='封面图')),
                ('is_new', models.BooleanField(default=False, verbose_name='是否新品')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热销')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
                'ordering': ['-ctime'],
            },
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='goods/detail/images', verbose_name='图片')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品轮播',
                'verbose_name_plural': '商品轮播',
                'ordering': ['-ctime'],
            },
        ),
        migrations.AddIndex(
            model_name='goods',
            index=models.Index(fields=['name'], name='goods_name_idx'),
        ),
        migrations.AddIndex(
            model_name='goods',
            index=models.Index(fields=['shop_price'], name='shop_price_idx'),
        ),
        migrations.AddIndex(
            model_name='goods',
            index=models.Index(fields=['is_new'], name='is_new_idx'),
        ),
        migrations.AddIndex(
            model_name='goods',
            index=models.Index(fields=['is_hot'], name='is_hot_idx'),
        ),
        migrations.AddField(
            model_name='banner',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='商品'),
        ),
    ]
