# Generated by Django 3.1.2 on 2020-12-15 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('trade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.useraddress', verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='goods',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.orderinfo', verbose_name='订单信息'),
        ),
        migrations.AddIndex(
            model_name='shoppingcart',
            index=models.Index(fields=['goods'], name='cart_goods_idx'),
        ),
        migrations.AddIndex(
            model_name='orderinfo',
            index=models.Index(fields=['order_sn'], name='order_sn_idx'),
        ),
        migrations.AddIndex(
            model_name='orderinfo',
            index=models.Index(fields=['pay_status'], name='pay_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ordergoods',
            index=models.Index(fields=['order'], name='order_idx'),
        ),
        migrations.AddIndex(
            model_name='ordergoods',
            index=models.Index(fields=['goods'], name='order_goods_idx'),
        ),
    ]
