# Generated by Django 3.1.2 on 2020-12-27 02:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20201218_1934'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='orderinfo',
            name='order_sn_idx',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='status_time',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='订单取消或完成时间'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='pay_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='支付时间'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.IntegerField(default=0, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_type',
            field=models.IntegerField(default=0, verbose_name='支付类型'),
        ),
    ]
