# Generated by Django 3.1.2 on 2020-12-27 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20201227_1039'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppingcart',
            unique_together=set(),
        ),
    ]
