# Generated by Django 3.1.2 on 2021-01-08 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20201227_1521'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='orderinfo',
            name='pay_status_idx',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='pay_status',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'Unpaid'), (2, 'Paid'), (3, 'Success'), (4, 'Cancel'), (5, 'Invalid')], default=1, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_goods', to='trade.orderinfo', verbose_name='订单信息'),
        ),
        migrations.AddIndex(
            model_name='orderinfo',
            index=models.Index(fields=['order_status'], name='order_status_idx'),
        ),
    ]
