# Generated by Django 3.1.2 on 2021-01-08 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201218_1934'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='useraddress',
            name='phone_idx',
        ),
    ]
